apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: {{ .Values.namespace }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World</title>
    </head>
    <body>
    <h1>{{ .Values.h1Content }}</h1>
    </body>
    </html>