apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nginx-hello
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
