name: Deploy Nginx Hello Helm

on:
  workflow_dispatch:
    inputs:
      h1Content:
        description: 'Content for the H1 tag'
        required: true
        default: 'Hello from GitHub Actions'
      pipelineID:
        description: 'Optional unique pipeline ID for Ingress host'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Kubernetes tools
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.6'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.17.0'

      - name: Configure kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECONFIG_DATA" | base64 --decode > $HOME/.kube/config

      - name: Generate Helm template
        run: |
          # Użyj podanego pipelineID lub automatycznie github.run_id
          PIPELINE_ID="${{ github.event.inputs.pipelineID }}"
          if [ -z "$PIPELINE_ID" ]; then
            PIPELINE_ID="${{ github.run_id }}"
          fi

          echo "Using PIPELINE_ID: $PIPELINE_ID"
          
          ls -la
          
          helm template my-nginx ./statslab-poc \
            --namespace default \
            --set h1Content="${{ github.event.inputs.h1Content }}" \
            --set pipelineID="$PIPELINE_ID" \
            > helm-output.yaml

      - name: Apply manifests to Kubernetes
        run: |
          kubectl apply -f helm-output.yaml
