name: Deploy Nginx Hello Helm

on:
  workflow_dispatch:
    inputs:
      h1Content:
        description: 'Content for the H1 tag'
        required: true
        default: 'Hello from GitHub Actions'
      pipelineID:
        description: 'Optional unique pipeline ID for Ingress host'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: [self-hosted, kubernetes, dev-deployment]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.6'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.17.0'

      - name: Setup kubeconfig for runner
        run: |
          # Create kubeconfig manually in /tmp (writable directory)
          mkdir -p /tmp/.kube
          
          # Get Kubernetes API server details
          API_SERVER="https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT"
          TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace || echo "default")
          
          # Create kubeconfig
          cat > /tmp/.kube/config << EOF
          apiVersion: v1
          kind: Config
          current-context: runner-context
          contexts:
          - context:
              cluster: local-cluster
              namespace: $NAMESPACE
              user: runner-user
            name: runner-context
          clusters:
          - cluster:
              certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              server: $API_SERVER
            name: local-cluster
          users:
          - name: runner-user
            user:
              token: $TOKEN
          EOF
          
          # Set KUBECONFIG environment variable
          export KUBECONFIG=/tmp/.kube/config
          echo "KUBECONFIG=/tmp/.kube/config" >> $GITHUB_ENV
          
          # Test kubectl connection
          kubectl version --client
          echo "✅ kubectl configured successfully"

      - name: Generate Helm template and deploy
        run: |
          # Użyj podanego pipelineID lub automatycznie github.run_id
          PIPELINE_ID="${{ github.event.inputs.pipelineID }}"
          if [ -z "$PIPELINE_ID" ]; then
            PIPELINE_ID="${{ github.run_id }}"
          fi
          
          # Use deployment namespace with prefix
          NAMESPACE="app-dev-pr-${PIPELINE_ID}"

          echo "Using PIPELINE_ID: $PIPELINE_ID"
          echo "Deploying to namespace: $NAMESPACE"
          
          # Create namespace if it doesn't exist
          kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
          
          # Deploy using Helm
          helm upgrade --install nginx-${PIPELINE_ID} . \
            --namespace "$NAMESPACE" \
            --set h1Content="${{ github.event.inputs.h1Content }}" \
            --set pipelineID="$PIPELINE_ID" \
            --set namespace="$NAMESPACE" \
            --timeout=5m \
            --wait
            
      - name: Show deployment info
        run: |
          PIPELINE_ID="${{ github.event.inputs.pipelineID }}"
          if [ -z "$PIPELINE_ID" ]; then
            PIPELINE_ID="${{ github.run_id }}"
          fi
          
          NAMESPACE="app-dev-pr-${PIPELINE_ID}"
          
          echo "🚀 Deployment completed!"
          echo "📦 Namespace: $NAMESPACE"
          echo "🌐 Application URL: https://${PIPELINE_ID}.dev.statslab.local"
          echo ""
          echo "📊 Pod status:"
          kubectl get pods -n "$NAMESPACE" -l app.kubernetes.io/instance=nginx-${PIPELINE_ID}
          echo ""
          echo "🔗 Service status:"
          kubectl get svc -n "$NAMESPACE" -l app.kubernetes.io/instance=nginx-${PIPELINE_ID}
          echo ""
          echo "🌍 Ingress status:"
          kubectl get ingress -n "$NAMESPACE" -l app.kubernetes.io/instance=nginx-${PIPELINE_ID}
